import "./globals.css";
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        suppressHydrationWarning={true}
        style={{
          backgroundColor: '#050505',
          color: '#fafafa',
          margin: 0,
          padding: 0,
          boxSizing: 'border-box'
        }}
      >
        {children}
      </body>
    </html>
  );
}
